import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export default defineSchema({
    rooms: defineTable({
        code: v.string(),
        status: v.union(v.literal('lobby'), v.literal('playing'), v.literal('finished')),
        activePlayerId: v.optional(v.id('players')),
        remainingMoves: v.number(),
        lastRoll: v.optional(v.array(v.number())),
        message: v.string(),
        round: v.number(),
        phase: v.optional(
            v.union(
                v.literal('awaitingRoll'),
                v.literal('moving'),
                v.literal('revealingEncounter'),
                v.literal('shopping'),
            ),
        ),
        activeEncounterId: v.optional(v.id('encounters')),
        shopKind: v.optional(
            v.union(
                v.literal('armoury'),
                v.literal('jeweller'),
                v.literal('weapons'),
                v.literal('items'),
                v.literal('magic'),
            ),
        ),
    }).index('by_code', ['code']),
    players: defineTable({
        roomId: v.id('rooms'),
        name: v.string(),
        color: v.string(),
        position: v.number(),
        previousPosition: v.optional(v.number()),
        gold: v.number(),
        hp: v.number(),
        maxHp: v.number(),
        attack: v.number(),
        dice: v.array(v.number()),
        joinedAt: v.number(),
    }).index('by_room', ['roomId']),
    encounters: defineTable({
        roomId: v.id('rooms'),
        playerId: v.id('players'),
        spaceId: v.number(),
        kind: v.union(v.literal('combat'), v.literal('event')),
        outcomeId: v.string(),
        title: v.string(),
        description: v.string(),
        goldDelta: v.number(),
        hpDelta: v.number(),
        wheelIndex: v.number(),
        status: v.union(v.literal('revealing'), v.literal('resolved')),
        createdAt: v.number(),
    }).index('by_roomId', ['roomId']),
    playerItems: defineTable({
        playerId: v.id('players'),
        itemId: v.string(),
        equippedSlot: v.optional(
            v.union(
                v.literal('weapon'),
                v.literal('helmet'),
                v.literal('body'),
                v.literal('gloves'),
                v.literal('boots'),
                v.literal('cape'),
                v.literal('amulet'),
                v.literal('ringLeft'),
                v.literal('ringRight'),
            ),
        ),
        purchasedAt: v.number(),
    }).index('by_playerId', ['playerId']),
    gameEvents: defineTable({
        type: v.string(),
        subjects: v.any(),
        data: v.any(),
        createdAt: v.number(),
    }).index('by_createdAt', ['createdAt']),
    roomCameras: defineTable({
        roomId: v.id('rooms'),
        mode: v.union(v.literal('follow'), v.literal('free')),
        targetX: v.number(),
        targetZ: v.number(),
        distance: v.number(),
        updatedAt: v.number(),
    }).index('by_roomId', ['roomId']),
})
