import Mythroads.Compile.Code

/-!
# The driver: closure, assembly and the failure conditions

`compileEngine` starts from a list of root declarations, translates each one, and keeps
translating whatever they mention until nothing is left. The result is a single
TypeScript module: the runtime shims, then every type reached, then every function
reached, in discovery order.

## Three ways this fails the build, all of them loud

1. **An unshimmed primitive.** An `@[extern]` declaration has no LCNF body to compile.
   Emitting a call to it anyway would produce a file that references a function nobody
   defined, so the compiler refuses instead.
2. **A name collision.** Shortening `Mythroads.Engine.Lobby.join` to `Lobby_join` could
   in principle collide with another declaration; two Lean names claiming one
   TypeScript identifier is refused rather than silently shadowed.
3. **A literal above 2^53.** `Nat` is a `number`, so a literal that a double cannot
   represent exactly is refused. Nothing in the engine comes close today.

## The line limit

The emitted module is one file of several thousand lines, which is far above the
300-line limit `npm run check:architecture` puts on hand-written source. That limit
exists so that a person maintaining a file can hold it in their head; nobody maintains
this one, and splitting it would mean cutting a strongly connected call graph across
module boundaries for no benefit. `scripts/quality/architecture.config.mjs` therefore
names this one path — and only this one — as exempt from the line limit. Every other
check, including Biome's lint and format rules and `tsc --strict`, still applies.
-/

namespace Mythroads.Compile

open Lean Lean.Compiler.LCNF

/-- Translate one declaration into an exported TypeScript function. -/
def emitDecl (n : Name) : M Unit := do
  if (← get).done.contains n then return
  modify fun s => { s with done := s.done.insert n }
  let some d ← getDeclAt? n .mono | recordMissing n
  modify fun s => { s with ctx := {}, current := n }
  match d.value with
  | .extern _ => recordMissing n
  | .code code =>
      let d ← CompilerM.run (phase := .mono) (normalizeFVarIds d)
      let code := match d.value with | .code c => c | _ => code
      modify fun s => { s with counts := countCode {} code }
      let id ← claimIdent "value" n
      let mut typed := #[]
      for p in d.params do
        let name ← bindFVar p.fvarId p.binderName
        let ty ← tsType p.type
        noteType p.fvarId ty
        unless p.type.isErased do typed := typed.push (name, ty)
      let result ← tsType (resultType d.type d.params.size)
      modify fun s => { s with resultTy := result }
      let body ← emitCode code "  "
      let shown := hideUnused body typed
      let params := String.intercalate ", " (shown.toList.map fun (id, ty) => s!"{id}: {ty}")
      let txt := s!"/** Lean `{n}`. */\nexport function {id}({params}): {result} \{\n{body}}\n"
      modify fun s => { s with fns := s.fns.push txt }

/-- Drain both work queues until the reachable closure of the roots is translated. -/
partial def drain : M Unit := do
  let st ← get
  if st.queue.size > 0 then
    let n := st.queue[0]!
    modify fun s => { s with queue := s.queue.extract 1 s.queue.size }
    emitDecl n
    drain
  else if st.typeQueue.size > 0 then
    let n := st.typeQueue[0]!
    modify fun s => { s with typeQueue := s.typeQueue.extract 1 s.typeQueue.size }
    emitType n
    drain

/-- Lean abbreviations worth restating as named TypeScript aliases for the adapter. -/
def aliasRoots : List Name :=
  [`Mythroads.Engine.Outcome, `Mythroads.Engine.NodeId, `Mythroads.PlayerId,
    `Mythroads.AuthId, `Mythroads.ItemId]

/-- The comment that opens the generated module. -/
def fileHeader : String :=
"/**
 * The Mythroads engine, compiled from Lean.
 *
 * `proofs/Mythroads/Engine/**` is the definition of the game; `lake exe mythroads-compile`
 * translates the monomorphised compiler IR of `Mythroads.Engine.step` and everything it
 * reaches into the TypeScript below. Do not edit this file: run `npm run proofs:generate`.
 *
 * Representation:
 * - a Lean structure is a plain object;
 * - a many-constructor inductive is a union tagged with `_`, as in `{ _: \"lobby\" }`;
 * - `List` is an array, `Nat` and `Int` are `number`, `String` is `string`;
 * - `Option` is `{ _: \"none\" }` or `{ _: \"some\", val }`, never `undefined`.
 *
 * `step(state, envelope)` returns `Except<Error, Prod<State, Effect[]>>`: either
 * `{ _: \"error\", a: <error> }` or `{ _: \"ok\", a: { fst: <next state>, snd: <effects> } }`.
 * Both `Except` constructors name their payload `a` and `Prod` names its parts `fst` and
 * `snd`, because field names are Lean's binder names and nothing here renames them.
 * `step` is pure and total; the caller persists the effects and stores the new state.
 *
 * `tests/engine/engine-parity.test.ts` checks this file against the Lean `step` itself,
 * scenario by scenario and over a seeded fuzz, by exact JSON.
 */
"

/-- Compile the reachable closure of `roots` into one TypeScript module. -/
def compileEngine (roots : List Name) : M String := do
  for r in roots do requestDecl r
  drain
  let mut aliases := #[]
  for a in aliasRoots do
    if (← getEnv).find? a |>.isSome then
      aliases := aliases.push s!"/** Lean `{a}`. */\nexport type {tsIdent a} = {← tsType (mkConst a)};\n"
  drain
  let st ← get
  let body := String.intercalate "\n" (st.tys.toList ++ aliases.toList ++ st.fns.toList)
  return String.intercalate "\n" [fileHeader, runtimeFor body, body]

/-- Every top-level identifier the compiler claimed, which the second pass keeps clear. -/
def claimedIdents (st : St) : Std.HashSet String :=
  st.claimed.fold (fun acc key _ => acc.insert ((key.splitOn ":").getLast!)) {}

/-- A description of everything that makes the output untrustworthy, or `none` if it is clean. -/
def failures (st : St) : Option String :=
  let missing :=
    if st.missing.isEmpty then []
    else st.missing.toList.map fun (n, from_) =>
      s!"no shim for the primitive {n}, reached from {from_}"
  let collisions := st.collisions.toList.map fun (id, a, b) =>
    s!"identifier {id} is claimed by both {a} and {b}"
  match missing ++ collisions with
  | [] => none
  | problems => some (String.intercalate "\n" problems)

end Mythroads.Compile
