import Mythroads.Convex.TypeScript

namespace Mythroads.Convex

/-! # Typed database expressions

Every emitted `ctx.db` call used to be built by hand from `Expr` constructors with the table name
as a bare string, and every `withIndex` chain restated both the index name and its key fields. The
helpers here take a `Table` and an `Index` instead, so the emitted text is derived from the schema
rather than agreeing with it by inspection.

`indexedRead` is the important one: the `q.eq(…)` chain is built by zipping `Index.fields` with the
supplied key expressions, so an emitter cannot name a field the index does not have, cannot reorder
the keys, and cannot query an index that belongs to another table.

`Terminal` names the query terminator. `.collect` is unbounded and therefore carries the reason it
is allowed, so every unbounded read writes its justification into the Lean source.
-/

namespace Query

open TypeScript

/-- `ctx.db`. -/
def db : Expr := .property (.identifier "ctx") "db"

/-- The comparison an indexed read applies to its final key. Earlier keys are always equalities,
which is what a Convex index range requires. -/
inductive Bound where
  /-- `q.eq(field, value)`. -/
  | eq
  /-- `q.lt(field, value)`, used by the retention sweep. -/
  | lt

/-- The builder method for a bound. -/
def Bound.method : Bound → String
  | .eq => "eq"
  | .lt => "lt"

/-- How an indexed query ends. -/
inductive Terminal where
  /-- `.unique()`. -/
  | unique
  /-- `.first()`. -/
  | first
  /-- `.take(limit)`, the bounded read this codebase prefers. -/
  | take (limit : Nat)
  /-- `.collect()`, unbounded; `reason` records why the result set is known to be small. -/
  | collect (reason : String)

/-- `ctx.db.query('table')`. -/
def scan (table : Table) : Expr := .call (.property db "query") [.string table.name]

/-- `ctx.db.get(id)`. The single-argument overload, for the sites where the emitter holds an id
whose table is only known to TypeScript (a `Doc<'rooms'>` field, say). -/
def get (id : Expr) : Expr := .await (.call (.property db "get") [id])

/-- `ctx.db.get('table', id)`. Convex documents this table-qualified overload as the preferred one
because it disambiguates the document type, so prefer it whenever the table is known here. -/
def getIn (table : Table) (id : Expr) : Expr :=
  .await (.call (.property db "get") [.string table.name, id])

/-- `ctx.db.patch('table', id, fields)`, the table-qualified overload. -/
def patchIn (table : Table) (id fields : Expr) : Expr :=
  .await (.call (.property db "patch") [.string table.name, id, fields])

/-- `ctx.db.delete('table', id)`, the table-qualified overload. -/
def removeIn (table : Table) (id : Expr) : Expr :=
  .await (.call (.property db "delete") [.string table.name, id])

/-- `ctx.db.insert('table', document)`. -/
def insert (table : Table) (document : Expr) : Expr :=
  .await (.call (.property db "insert") [.string table.name, document])

/-- `ctx.db.patch(id, fields)`. -/
def patch (id fields : Expr) : Expr :=
  .await (.call (.property db "patch") [id, fields])

/-- `ctx.db.replace(id, document)`. -/
def replace (id document : Expr) : Expr :=
  .await (.call (.property db "replace") [id, document])

/-- `ctx.db.delete(id)`. -/
def remove (id : Expr) : Expr := .await (.call (.property db "delete") [id])

/-- `schema.doc('table')`, the validator for a whole stored document. -/
def schemaDoc (table : Table) : Expr :=
  .call (.property (.identifier "schema") "doc") [.string table.name]

/-- Applies the terminator to a query builder expression. -/
def terminate (query : Expr) : Terminal → Expr
  | .unique => .await (.call (.property query "unique") [])
  | .first => .await (.call (.property query "first") [])
  | .take limit => .await (.call (.property query "take") [.number limit])
  | .collect _ => .await (.call (.property query "collect") [])

/-- An indexed read. The `q.eq(…)` chain is built from `index.fields` zipped with `keys`, so the
key order and field names come from the schema and not from the call site. The lambda binder is
named `binder` because the existing emitters are not consistent about `q` versus `query`, and the
generated bytes must not change. -/
def indexedRead (table : Table) (index : Index table) (keys : List Expr)
    (terminal : Terminal) (binder : String := "query") (bound : Bound := .eq) : Expr :=
  let pairs := index.fields.zip keys
  let predicate := (pairs.zipIdx).foldl
    (fun acc ((field, key), position) =>
      let relation := if position + 1 == pairs.length then bound else .eq
      .call (.property acc relation.method) [.string field, key])
    (.identifier binder)
  terminate (.call (.property (scan table) "withIndex")
    [.string index.name, .arrow [binder] predicate]) terminal

end Query
end Mythroads.Convex
